import React from 'react';

export const metadata = {
  title: 'Ariful -  Blog',
  description: 'Generated by create next app',
};

const Blog = () => {
  return <div>Blog</div>;
};

export default Blog;
