import React from 'react';
import Slider from '../components/home/Slider';

export const metadata = {
  title: 'Ariful - Portfolio',
  description: 'Generated by create next app',
};

const Portfolio = () => {
  return (
    <div>
      Portfolio
      {/* <Slider /> */}
    </div>
  );
};

export default Portfolio;
