import React from 'react';


export const metadata = {
  title: 'Ariful - Resume',
  description: 'Generated by create next app',
};
const Resume = () => {
  return (
    <div>
      Resume
    </div>
  );
};

export default Resume;